### ISSUE TITLE
New Release for experimental package

### ISSUE THREAD

**Issue by JordanMartinez** [FXMisc/WellBehavedFX#2]
Is there any additional work you need to do for the experimental `InputMap` API? Or can a new release be made that includes it so we can integrate it into `RichTextFX`?

**Comment by TomasMikula** [comment]
The intention is for the experimental package (`org.fxmisc.wellbehaved.event.experimental`) to replace the current package (`org.fxmisc.wellbehaved.event`). I guess before doing that, I wanted to sanity-check that everything that is possible with the current package is possible with the experimental package. My way of doing that would be to try to port RichTextFX to the experimental package. If everything goes well, I would be confident to make the `experimental` package replace the current one for good.

**Comment by JordanMartinez** [comment]
I should have known: we did the same thing in RichTextFX with Flowless when removing the skin.

I'm currently working more on my own code, so I might have time to try this at the end of this week. Not sure yet. No doubt I'll be following [your use cases document](https://htmlpreview.github.io/?https://github.com/TomasMikula/InputMapAPI/blob/master/use-cases.html) as a guide. Once implemented, we should probably include a demo in RichTextFX that shows how to override the default event handling. Or perhaps include that demo in this package and link to it from RichTextFX.

**Comment by JordanMartinez** [comment]
A new release was made, so this issue can be closed.
